name: Deploy to OpenShift

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest	
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: docker build -t quay.io/kateli1123/springboot-app:latest .

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push quay.io/kateli1123/springboot-app:latest

    - name: Install oc CLI
      run: |
        curl -L https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz | tar xz
        sudo mv oc /usr/local/bin/

    - name: Login to OpenShift
      run: oc login --token=${{ secrets.OC_LOGIN_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER_URL }}

    - name: Deploy to OpenShift
      run: |
        oc project ${{ secrets.OPENSHIFT_NAMESPACE }}
        oc apply -f openshift.yaml
        oc rollout restart deployment/springboot-app